routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// 后台登陆
Route::group(['namespace' => 'Auth'], function () {
    Route::get('login', 'LoginController@showLoginForm')->name('login');
    Route::post('login', 'LoginController@login');
    Route::post('logout', 'LoginController@logout')->name('logout');
    Route::get('password/reset', 'ForgotPasswordController@showLinkRequestForm')->name('password.request');
    Route::post('password/email', 'ForgotPasswordController@sendResetLinkEmail')->name('password.email');
    Route::get('password/reset/{token}', 'ResetPasswordController@showResetForm')->name('password.reset');
    Route::post('password/reset', 'ResetPasswordController@reset');
    // 第三方登录
    Route::group(['prefix' => 'oauth'], function () {
        // 重定向
        Route::get('redirect/{service}', 'OAuthController@redirectToProvider')->name('oauth.redirect');
        // 获取用户资料并登录
        Route::get('callback/{service}', 'OAuthController@handleProviderCallback')->name('oauth.callback');
        // 退出登录
        Route::get('logout', 'OAuthController@logout');
    });
    Route::post('hook/{type}', 'HookController@push');
});

// 前台
Route::group(['namespace' => 'Home', 'middleware' => ['check_status']], function () {
    Route::get('/', 'HomeController@index')->name('home');
    Route::get('about', 'HomeController@about')->name('about');
    Route::get('article/{id}', 'HomeController@article')->name('article');
    Route::get('page/{id}', 'HomeController@page')->name('page');
    Route::post('comment_store', 'HomeController@comment_store')->name('comment_store');
    Route::get('category/{id}', 'HomeController@category')->name('category');
    Route::get('tag/{id}', 'HomeController@tag')->name('tag');
    Route::get('archive', 'HomeController@archive')->name('archive');
    Route::get('message', 'HomeController@message')->name('message');
    Route::post('message_store', 'HomeController@message_store')->name('message_store');
    Route::get('subscribe', 'HomeController@subscribe')->name('subscribe');
    Route::post('subscribe_store', 'HomeController@subscribe_store')->name('subscribe_store');
    Route::get('search', 'HomeController@search')->name('search');
});
// 后台
Route::group(['namespace' => 'Admin', 'prefix' => 'admin', 'middleware' => ['auth:web', 'check_timeout', 'check_permission']], function () {
    // 权限管理
    Route::group(['namespace' => 'Permission'], function () {
        // 角色
        Route::group(['prefix' => 'role'], function () {
            Route::get('manage', 'RoleController@manage')->name('role_manage');
            Route::post('store', 'RoleController@store')->name('role_store');
            Route::get('edit/{id}', 'RoleController@edit')->name('role_edit');
            Route::post('update/{id}', 'RoleController@update')->name('role_update');
            Route::post('destroy', 'RoleController@destroy')->name('role_destroy');
            Route::get('search', 'RoleController@search')->name('role_search');
        });
        // 权限
        Route::group(['prefix' => 'permission'], function () {
            Route::get('manage', 'PermissionController@manage')->name('permission_manage');
            Route::post('store', 'PermissionController@store')->name('permission_store');
            Route::get('edit/{id?}', 'PermissionController@edit')->name('permission_edit');
            Route::post('update', 'PermissionController@update')->name('permission_update');
            Route::post('destroy', 'PermissionController@destroy')->name('permission_destroy');
            Route::get('search', 'PermissionController@search')->name('permission_search');
        });
        // 用户
        Route::group(['prefix' => 'user'], function () {
            Route::get('manage', 'UserController@manage')->name('user_manage');
            Route::get('create', 'UserController@create')->name('user_create');
            Route::post('store', 'UserController@store')->name('user_store');
            Route::get('edit/{id}', 'UserController@edit')->name('user_edit');
            Route::post('update/{id}', 'UserController@update')->name('user_update');
            Route::post('delete', 'UserController@delete')->name('user_delete');
            Route::get('trash', 'UserController@trash')->name('user_trash');
            Route::post('restore', 'UserController@restore')->name('user_restore');
            Route::post('destroy', 'UserController@destroy')->name('user_destroy');
            Route::get('search', 'UserController@search')->name('user_search');
        });
    });
    // 控制台
    Route::get('/', function () {
        return redirect()->route('dashboard_home');
    });
    Route::get('home', 'DashboardController@home')->name('dashboard_home');
    Route::get('clear', 'DashboardController@clear')->name('cache_clear');
    // 配置
    Route::group(['prefix' => 'config'], function () {
        Route::get('manage', 'ConfigController@manage')->name('config_manage');
        Route::post('update', 'ConfigController@update')->name('config_update');
        Route::post('upload-image', 'ConfigController@uploadImage')->name('water_mark_upload');
    });
    // 个人资料
    Route::group(['prefix' => 'profile'], function () {
        Route::get('manage', 'ProfileController@manage')->name('profile_manage');
        Route::post('uploadAvatar', 'ProfileController@uploadAvatar')->name('avatar_upload');
        Route::post('updatePassword', 'ProfileController@updatePassword')->name('password_update');
        Route::post('updateProfile', 'ProfileController@updateProfile')->name('profile_update');
        Route::post('unbindThirdLogin', 'ProfileController@unbindThirdLogin')->name('unbind_third_login');
    });
    // 标签
    Route::group(['prefix' => 'tag'], function () {
        Route::get('manage', 'TagController@manage')->name('tag_manage');
        Route::post('store', 'TagController@store')->name('tag_store');
        Route::get('edit/{id?}', 'TagController@edit')->name('tag_edit');
        Route::post('update', 'TagController@update')->name('tag_update');
        Route::post('destroy', 'TagController@destroy')->name('tag_destroy');
        Route::get('search', 'TagController@search')->name('tag_search');
    });
    // 栏目
    Route::group(['prefix' => 'category'], function () {
        Route::get('manage', 'CategoryController@manage')->name('category_manage');
        Route::get('create', 'CategoryController@create')->name('category_create');
        Route::post('store', 'CategoryController@store')->name('category_store');
        Route::get('edit/{id}', 'CategoryController@edit')->name('category_edit');
        Route::post('update/{id}', 'CategoryController@update')->name('category_update');
        Route::post('destroy', 'CategoryController@destroy')->name('category_destroy');
    });
    // 菜单
    Route::group(['prefix' => 'nav'], function () {
        Route::get('manage', 'NavController@manage')->name('nav_manage');
        Route::get('create', 'NavController@create')->name('nav_create');
        Route::post('store', 'NavController@store')->name('nav_store');
        Route::get('edit/{id}', 'NavController@edit')->name('nav_edit');
        Route::post('update/{id}', 'NavController@update')->name('nav_update');
        Route::post('destroy', 'NavController@destroy')->name('nav_destroy');
    });
    // 文章
    Route::group(['prefix' => 'article'], function () {
        Route::get('manage', 'ArticleController@manage')->name('article_manage');
        Route::get('create', 'ArticleController@create')->name('article_create');
        Route::post('store', 'ArticleController@store')->name('article_store');
        Route::get('edit/{id}', 'ArticleController@edit')->name('article_edit');
        Route::post('update/{id}', 'ArticleController@update')->name('article_update');
        Route::post('delete', 'ArticleController@delete')->name('article_delete');
        Route::get('trash', 'ArticleController@trash')->name('article_trash');
        Route::post('restore', 'ArticleController@restore')->name('article_restore');
        Route::post('destroy', 'ArticleController@destroy')->name('article_destroy');
        Route::post('upload-image', 'ArticleController@uploadImage')->name('article_image_upload');

    });
    // 单页
    Route::group(['prefix' => 'page'], function () {
        Route::get('manage', 'PageController@manage')->name('page_manage');
        Route::get('create', 'PageController@create')->name('page_create');
        Route::post('store', 'PageController@store')->name('page_store');
        Route::get('edit/{id}', 'PageController@edit')->name('page_edit');
        Route::post('update/{id}', 'PageController@update')->name('page_update');
        Route::post('delete', 'PageController@delete')->name('page_delete');
        Route::get('trash', 'PageController@trash')->name('page_trash');
        Route::post('restore', 'PageController@restore')->name('page_restore');
        Route::post('destroy', 'PageController@destroy')->name('page_destroy');
    });
    // 评论
    Route::group(['prefix' => 'comment'], function () {
        Route::get('manage', 'CommentController@manage')->name('comment_manage');
        Route::get('show/{id?}', 'CommentController@show')->name('comment_show');
        Route::post('check', 'CommentController@check')->name('comment_check');
        Route::post('reply', 'CommentController@reply')->name('comment_reply');
        Route::post('destroy', 'CommentController@destroy')->name('comment_destroy');
    });
    // 友链
    Route::group(['prefix' => 'link'], function () {
        Route::get('manage', 'LinkController@manage')->name('link_manage');

app/Models/Nav.php
<?php

namespace App\Models;

class Nav extends Base
{
    const TYPE = [
        0 => '空菜单',
        1 => '分类菜单',
        2 => '归档',
        3 => '单页',
        4 => '外链',
    ];
    const TYPE_EMPTY = 0;    // 普通菜单 可添加单页 链接
    const TYPE_MENU = 1;     // 分类菜单（固定存在的）
    const TYPE_ARCHIVE = 2;  // 归档页面（固定存在的）
    const TYPE_PAGE = 3;     // 单页（url为单页链接）
    const TYPE_LINK = 4;     // 链接（直接添加链接）
    const LIMIT_NUM = 14;    // 最大菜单数
    const STATUS_DISPLAY = 1;
    const STATUS_HIDE = 0;


    /**
     * 递归获取树形索引
     * @param integer
     * @param integer
     * @return array 角色数组
     */
    public function getTreeIndex($id = 0, $deep = 0)
    {
        static $tempArr = [];
        $data = $this->query()->where('parent_id', $id)->orderBy('sort', 'asc')->get();
        foreach ($data as $k => $v) {
            $v->deep = $deep;
            $v->name = str_repeat("&nbsp;&nbsp;", $v->deep * 2) . '|--' . $v->name;
            $tempArr[] = $v;
            $this->getTreeIndex($v->id, $deep + 1);
        }
        return $tempArr;
    }

    public function getTypeNameAttribute()
    {
        $result = "";
        foreach (self::TYPE as $key => $type) {
            if ($this->attributes['type'] == $key) {
                $result = $type;
            }
        }
        return $result;
    }

    public function getStatusTagAttribute()
    {
        return $this->attributes['status'] === self::STATUS_DISPLAY ? '<a href="javascript:void(0)" class="btn btn-sm btn-success btn-flat">显示</a>' : '<a href="javascript:void(0)" class="btn btn-sm btn-danger btn-flat">隐藏</a>';
    }
}

resources/views/admin/article-trash.blade.php
@extends('layouts.backend')
@section('title','控制台 - 文章回收站')
@section('content')
    <div class="content-wrapper">
        <section class="content-header">
            <h1>回收站<small>LABLOG</small></h1>
            <ol class="breadcrumb">
                <li><a href="{{ route('dashboard_home') }}"><i class="fa fa-dashboard"></i> 首页</a></li>
                <li><a href="{{ route('article_manage') }}">文章管理</a></li>
                <li class="active">文章回收站</li>
            </ol>
        </section>
        <section class="content container-fluid">
            <div class="row">
                <div class="col-md-12">
                    <div class="box">
                        <div class="box-header with-border">
                            <h3 class="box-title">文章回收站</h3>
                            <span>共 {{ $articles->total() }}篇</span>
                        </div>
                        <div class="box-body table-responsive no-padding">
                            <table class="table table-hover">
                                <thead>
                                <tr>
                                    <th>#</th>
                                    <th>标题</th>
                                    <th>删除时间</th>
                                    <th>操作</th>
                                </tr>
                                </thead>
                                <tbody>
                                @if(!blank($articles))
                                    @foreach($articles as $article)
                                        <tr>
                                            <td><input type="checkbox" value="{{$article->id}}" name="aid" class="i-checks"></td>
                                            <td>{{$article->title}}</td>
                                            <td>{{$article->deleted_at}}</td>
                                            <td>
                                                <a class="text-green restoreArticle"><i class="fa fa-recycle"></i></a>&nbsp;&nbsp;
                                                <a class="text-red destroyArticle"><i class="fa fa-trash"></i></a>
                                            </td>
                                        </tr>
                                    @endforeach
                                @else
                                    <tr><td valign="top" colspan="4">表中数据为空</td></tr>
                                @endif
                                </tbody>
                            </table>
                            <form id="restoreForm" style="display: none;" method="POST" action="{{route('article_restore')}}">
                                @csrf
                                <input type="hidden" name="aid" id="restoreId">
                            </form>
                            <form id="destroyForm" style="display: none;" method="POST" action="{{route('article_destroy')}}">
                                @csrf
                                <input type="hidden" name="aid" id="destroyId">
                            </form>
                        </div>
                        <div class="box-footer clearfix">
                            <div class="pull-left">
                                <a href="javascript:void(0)" class="btn btn-primary btn-flat" onclick="selectAll('aid')">全选</a>
                                <a href="javascript:void(0)" class="btn btn-primary btn-flat" onclick="selectEmpty('aid')">全不选</a>
                                <a href="javascript:void(0)" class="btn btn-primary btn-flat" onclick="selectReverse('aid')">反选</a>
                                <a href="javascript:void(0)" class="btn btn-danger btn-flat" id="destroySelectedArticle">彻底删除选定</a>
                                <a href="javascript:void(0)" class="btn btn-success btn-flat" id="restoreSelectedArticle">恢复选定</a>
                            </div>
                             {{ $articles->links('vendor.pagination.adminlte') }}
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>
@stop

resources/views/admin/nav-edit.blade.php
@extends('layouts.backend')
@section('title','控制台 - 菜单编辑')
@section('content')
    <div class="content-wrapper">
        <section class="content-header">
            <h1>菜单编辑<small>LABLOG</small></h1>
            <ol class="breadcrumb">
                <li><a href="{{ route('dashboard_home') }}"><i class="fa fa-dashboard"></i> 首页</a></li>
                <li><a href="{{ route('nav_manage') }}">菜单管理</a></li>
                <li class="active">菜单编辑</li>
            </ol>
        </section>
        <section class="content container-fluid">
            <div class="row">
                <div class="col-md-4">
                    <form role="form"  method="POST" action="{{ route('nav_update',$editNav->id)}}" id="editNavForm">
                        @csrf
                        <div class="box box-default">
                            <div class="box-header with-border">
                                <h3 class="box-title">编辑菜单</h3>
                            </div>
                            <div class="box-body">
                                <div class="form-group {{$errors->has('type')?'has-error':''}}">
                                    <label for="type">菜单类型：</label>
                                    <select class="form-control select2" name="type" id="type" >
                                        <option value="">菜单类型</option>
                                        @foreach (\App\Models\Nav::TYPE as $key => $type )
                                            <option value="{{ $key }}" @if (!is_null(old('type')) && old( 'type') == $key) selected="selected" @elseif( $editNav->type == $key) selected="selected" @endif>{{ $type }}</option>
                                        @endforeach
                                    </select>
                                    @if ($errors->has('type'))
                                        <span class="help-block "><strong><i class="fa fa-times-circle-o"></i>{{ $errors->first('type') }}</strong></span>
                                    @endif
                                </div>
                                <div class="form-group {{$errors->has('parent_id')?'has-error':''}}">
                                    <label for="parent_id">父级菜单</label>
                                    <select class="form-control select2" name="parent_id" id="parent_id">
                                        <option value="">请选择菜单</option>
                                        <option value="0" selected="selected">一级菜单</option>
                                        @foreach($emptyNavs as $empty_nav)
                                            <option value="{{ $empty_nav->id }}" @if (!is_null(old('parent_id')) && old( 'parent_id') ==  $empty_nav->id) selected="selected" @elseif( $editNav->parent_id == $empty_nav->id) selected="selected" @endif>{{ $empty_nav->name }}</option>
                                        @endforeach
                                    </select>
                                    <span class="help-block">仅可选空菜单类型，默认为1级菜单</span>
                                    @if ($errors->has('parent_id'))
                                        <span class="help-block "><strong><i class="fa fa-times-circle-o"></i>{{ $errors->first('parent_id') }}</strong></span>
                                    @endif
                                </div>
                                <div class="form-group {{$errors->has('name')?'has-error':''}}">
                                    <label for="name">菜单名：</label>
                                    <input type="text" class="form-control" name="name" id="name" placeholder="请输入菜单名称"  value="{{ old('name')?old('name'):$editNav->name }}">
                                    @if ($errors->has('name'))
                                        <span class="help-block "><strong><i class="fa fa-times-circle-o"></i>{{ $errors->first('name') }}</strong></span>
                                    @endif
                                </div>
                                <div class="form-group {{$errors->has('url')?'has-error':''}}" id="url-group">
                                    <label for="url">链接：</label>
                                    <input type="text" class="form-control" name="url" id="url" placeholder="请输入链接"  value="{{ old('url')?old('url'):$editNav->url }}">
                                    <span class="help-block text-red">仅对链接菜单有效，链接前请加上协议(如:https://xxx.com)</span>
                                    @if ($errors->has('url'))
                                        <span class="help-block "><strong><i class="fa fa-times-circle-o"></i>{{ $errors->first('url') }}</strong></span>
                                    @endif
                                </div>
                                <div class="form-group {{$errors->has('sort')?'has-error':''}}">
                                    <label for="sort">排序权重：</label>
                                    <input type="text" class="form-control" name="sort" id="sort" placeholder="请输入数字，默认为1"  value="{{ old('sort')?old('sort'):$editNav->sort }}">
                                    @if ($errors->has('sort'))
                                        <span class="help-block "><strong><i class="fa fa-times-circle-o"></i>{{ $errors->first('sort') }}</strong></span>
                                    @endif
                                </div>
                                <div class="form-group {{$errors->has('status')?'has-error':''}}">
                                    <label>状态：</label>
                                    <div class="radio">
                                        <label class="i-checks">
                                            <input type="radio" name="status" value="{{ \App\Models\Nav::STATUS_DISPLAY }}"
                                                   @if(!is_null(old('status')) && old( 'status') == \App\Models\Nav::STATUS_DISPLAY) checked="checked" @elseif($editNav->status == \App\Models\Nav::STATUS_DISPLAY ) checked="checked"  @endif> &nbsp;显示
                                        </label>
                                        <label class="i-checks">
                                            <input type="radio" name="status" value="{{ \App\Models\Nav::STATUS_HIDE }}"
                                                   @if(!is_null(old('status')) && old( 'status') == \App\Models\Nav::STATUS_HIDE) checked="checked" @elseif($editNav->status == \App\Models\Nav::STATUS_HIDE ) checked="checked"  @endif> &nbsp;隐藏
                                        </label>
                                    </div>
                                    @if ($errors->has('status'))
                                        <span class="help-block "><strong><i class="fa fa-times-circle-o"></i>{{ $errors->first('status') }}</strong></span>
                                    @endif
                                </div>
                            </div>
                            <div class="box-footer">
                                <button type="submit" class="btn btn-success btn-flat">提交</button>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="col-md-8">
                    <div class="box">
                        <div class="box-header with-border">
                            <h3 class="box-title">全部菜单</h3>
                        </div>
                        <div class="box-body table-responsive no-padding">
                            <table class="table table-hover">
                                <tr>
                                    <th>#</th>
                                    <th>菜单名</th>
                                    <th>类型</th>
                                    <th>排序权重</th>
                                    <th>状态</th>
                                    <th>操作</th>
                                </tr>
                                @foreach($navs as $nav)
                                    <tr>
                                        <td><label><input type="checkbox" value="{{$nav->id}}" name="nid" class="i-checks"></label></td>
                                        <td>{!! $nav->name !!}</td>
                                        <td>
                                            {{$nav->type_name}}
                                        </td>
                                        <td>
                                            {{$nav->sort}}
                                        </td>
                                        <td>
                                            {!! $nav->status_tag !!}
                                        </td>
                                        <td>
                                            <a href="{{route('nav_edit',$nav->id)}}" class="text-green">
                                                <i class="fa fa-pencil-square-o"></i>
                                            </a>&nbsp;&nbsp;
                                            <a href="javascript:void(0)" class="text-red delNav">
                                                <i class="fa fa-trash"></i>
                                            </a>
                                        </td>
                                    </tr>
                                @endforeach
                            </table>
                            <form id="deleteForm" style="display: none;" action="{{route('nav_destroy')}}" method="post">
                                @csrf
                                <input type="hidden" name="nid" id="deleteId">
                            </form>
                        </div>
                        <div class="box-footer clearfix">
                            <div class="pull-left">
                                <a href="javascript:void(0)" class="btn btn-primary btn-flat" onclick="selectAll('nid')">全选</a>
                                <a href="javascript:void(0)" class="btn btn-primary btn-flat" onclick="selectEmpty('nid')">全不选</a>
                                <a href="javascript:void(0)" class="btn btn-primary btn-flat" onclick="selectReverse('nid')">反选</a>
                                <a href="javascript:void(0)" class="btn btn-danger btn-flat" id="delSelectedNav">删除选定</a>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
        </section>
    </div>
@stop
@section('js')
    <script>
        $(function () {
            let type_empty = "{{ \App\Models\Nav::TYPE_EMPTY }}";
            let type_menu = "{{ \App\Models\Nav::TYPE_MENU }}";
            let type_page = "{{ \App\Models\Nav::TYPE_PAGE }}";
            let type_archive = "{{ \App\Models\Nav::TYPE_ARCHIVE }}";
            $("#type").select2();
            let parent_id_select = $('#parent_id').select2();
            $("#type").on("change",function(){
                let type = $(this).val();
                console.log(type);
                if ( type_empty == type ||  type_menu == type ){
                    parent_id_select.val("0").trigger("change");
                    $("#url-group").attr("style","display:none");
                    $("#parent_id").attr("disabled","disabled");
                }else if( type_page == type )
                {
                    $("#url").attr("placeholder","请输入单页链接，或单页ID");
                    $("#url-group").removeAttr("style");
                    $("#parent_id").removeAttr("disabled");
                } else if( type_archive == type )
                {
                    $("#url-group").attr("style","display:none");
                    $("#parent_id").removeAttr("disabled");
                }else{
                    $("#url-group").removeAttr("style");
                    $("#parent_id").removeAttr("disabled");
                }
            });
        });
    </script>
@stop