routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// 后台登陆
Route::group(['namespace' => 'Auth'], function () {
    Route::get('login', 'LoginController@showLoginForm')->name('login');
    Route::post('login', 'LoginController@login');
    Route::post('logout', 'LoginController@logout')->name('logout');
    Route::get('password/reset', 'ForgotPasswordController@showLinkRequestForm')->name('password.request');
    Route::post('password/email', 'ForgotPasswordController@sendResetLinkEmail')->name('password.email');
    Route::get('password/reset/{token}', 'ResetPasswordController@showResetForm')->name('password.reset');
    Route::post('password/reset', 'ResetPasswordController@reset');
    // 第三方登录
    Route::group(['prefix' => 'oauth'], function () {
        // 重定向
        Route::get('redirect/{service}', 'OAuthController@redirectToProvider')->name('oauth.redirect');
        // 获取用户资料并登录
        Route::get('callback/{service}', 'OAuthController@handleProviderCallback')->name('oauth.callback');
        // 退出登录
        Route::get('logout', 'OAuthController@logout');
    });
    Route::post('hook/{type}', 'HookController@push');
});

// 前台
Route::group(['namespace' => 'Home', 'middleware' => ['check_status']], function () {
    Route::get('/', 'HomeController@index')->name('home');
    Route::get('about', 'HomeController@about')->name('about');
    Route::get('article/{id}', 'HomeController@article')->name('article');
    Route::get('page/{id}', 'HomeController@page')->name('page');
    Route::post('comment_store', 'HomeController@comment_store')->name('comment_store');
    Route::get('category/{id}', 'HomeController@category')->name('category');
    Route::get('tag/{id}', 'HomeController@tag')->name('tag');
    Route::get('archive', 'HomeController@archive')->name('archive');
    Route::get('message', 'HomeController@message')->name('message');
    Route::post('message_store', 'HomeController@message_store')->name('message_store');
    Route::get('subscribe', 'HomeController@subscribe')->name('subscribe');
    Route::post('subscribe_store', 'HomeController@subscribe_store')->name('subscribe_store');
    Route::get('search', 'HomeController@search')->name('search');
});
// 后台
Route::group(['namespace' => 'Admin', 'prefix' => 'admin', 'middleware' => ['auth:web', 'check_timeout', 'check_permission']], function () {
    // 权限管理
    Route::group(['namespace' => 'Permission'], function () {
        // 角色
        Route::group(['prefix' => 'role'], function () {
            Route::get('manage', 'RoleController@manage')->name('role_manage');
            Route::post('store', 'RoleController@store')->name('role_store');
            Route::get('edit/{id}', 'RoleController@edit')->name('role_edit');
            Route::post('update/{id}', 'RoleController@update')->name('role_update');
            Route::post('destroy', 'RoleController@destroy')->name('role_destroy');
            Route::get('search', 'RoleController@search')->name('role_search');
        });
        // 权限
        Route::group(['prefix' => 'permission'], function () {
            Route::get('manage', 'PermissionController@manage')->name('permission_manage');
            Route::post('store', 'PermissionController@store')->name('permission_store');
            Route::get('edit/{id?}', 'PermissionController@edit')->name('permission_edit');
            Route::post('update', 'PermissionController@update')->name('permission_update');
            Route::post('destroy', 'PermissionController@destroy')->name('permission_destroy');
            Route::get('search', 'PermissionController@search')->name('permission_search');
        });
        // 用户
        Route::group(['prefix' => 'user'], function () {
            Route::get('manage', 'UserController@manage')->name('user_manage');
            Route::get('create', 'UserController@create')->name('user_create');
            Route::post('store', 'UserController@store')->name('user_store');
            Route::get('edit/{id}', 'UserController@edit')->name('user_edit');
            Route::post('update/{id}', 'UserController@update')->name('user_update');
            Route::post('delete', 'UserController@delete')->name('user_delete');
            Route::get('trash', 'UserController@trash')->name('user_trash');
            Route::post('restore', 'UserController@restore')->name('user_restore');
            Route::post('destroy', 'UserController@destroy')->name('user_destroy');
            Route::get('search', 'UserController@search')->name('user_search');
        });
    });
    // 控制台
    Route::get('/', function () {
        return redirect()->route('dashboard_home');
    });
    Route::get('home', 'DashboardController@home')->name('dashboard_home');
    Route::get('clear', 'DashboardController@clear')->name('cache_clear');
    // 配置
    Route::group(['prefix' => 'config'], function () {
        Route::get('manage', 'ConfigController@manage')->name('config_manage');
        Route::post('update', 'ConfigController@update')->name('config_update');
        Route::post('upload-image', 'ConfigController@uploadImage')->name('water_mark_upload');
    });
    // 个人资料
    Route::group(['prefix' => 'profile'], function () {
        Route::get('manage', 'ProfileController@manage')->name('profile_manage');
        Route::post('uploadAvatar', 'ProfileController@uploadAvatar')->name('avatar_upload');
        Route::post('updatePassword', 'ProfileController@updatePassword')->name('password_update');
        Route::post('updateProfile', 'ProfileController@updateProfile')->name('profile_update');
        Route::post('unbindThirdLogin', 'ProfileController@unbindThirdLogin')->name('unbind_third_login');
    });
    // 标签
    Route::group(['prefix' => 'tag'], function () {
        Route::get('manage', 'TagController@manage')->name('tag_manage');
        Route::post('store', 'TagController@store')->name('tag_store');
        Route::get('edit/{id?}', 'TagController@edit')->name('tag_edit');
        Route::post('update', 'TagController@update')->name('tag_update');
        Route::post('destroy', 'TagController@destroy')->name('tag_destroy');
        Route::get('search', 'TagController@search')->name('tag_search');
    });
    // 栏目
    Route::group(['prefix' => 'category'], function () {
        Route::get('manage', 'CategoryController@manage')->name('category_manage');
        Route::get('create', 'CategoryController@create')->name('category_create');
        Route::post('store', 'CategoryController@store')->name('category_store');
        Route::get('edit/{id}', 'CategoryController@edit')->name('category_edit');
        Route::post('update/{id}', 'CategoryController@update')->name('category_update');
        Route::post('destroy', 'CategoryController@destroy')->name('category_destroy');
    });
    // 菜单
    Route::group(['prefix' => 'nav'], function () {
        Route::get('manage', 'NavController@manage')->name('nav_manage');
        Route::get('create', 'NavController@create')->name('nav_create');
        Route::post('store', 'NavController@store')->name('nav_store');
        Route::get('edit/{id}', 'NavController@edit')->name('nav_edit');
        Route::post('update/{id}', 'NavController@update')->name('nav_update');
        Route::post('destroy', 'NavController@destroy')->name('nav_destroy');
    });
    // 文章
    Route::group(['prefix' => 'article'], function () {
        Route::get('manage', 'ArticleController@manage')->name('article_manage');
        Route::get('create', 'ArticleController@create')->name('article_create');
        Route::post('store', 'ArticleController@store')->name('article_store');
        Route::get('edit/{id}', 'ArticleController@edit')->name('article_edit');
        Route::post('update/{id}', 'ArticleController@update')->name('article_update');
        Route::post('delete', 'ArticleController@delete')->name('article_delete');
        Route::get('trash', 'ArticleController@trash')->name('article_trash');
        Route::post('restore', 'ArticleController@restore')->name('article_restore');
        Route::post('destroy', 'ArticleController@destroy')->name('article_destroy');
        Route::post('upload-image', 'ArticleController@uploadImage')->name('article_image_upload');

    });
    // 单页
    Route::group(['prefix' => 'page'], function () {
        Route::get('manage', 'PageController@manage')->name('page_manage');
        Route::get('create', 'PageController@create')->name('page_create');
        Route::post('store', 'PageController@store')->name('page_store');
        Route::get('edit/{id}', 'PageController@edit')->name('page_edit');
        Route::post('update/{id}', 'PageController@update')->name('page_update');
        Route::post('delete', 'PageController@delete')->name('page_delete');
        Route::get('trash', 'PageController@trash')->name('page_trash');
        Route::post('restore', 'PageController@restore')->name('page_restore');
        Route::post('destroy', 'PageController@destroy')->name('page_destroy');
    });
    // 评论
    Route::group(['prefix' => 'comment'], function () {
        Route::get('manage', 'CommentController@manage')->name('comment_manage');
        Route::get('show/{id?}', 'CommentController@show')->name('comment_show');
        Route::post('check', 'CommentController@check')->name('comment_check');
        Route::post('reply', 'CommentController@reply')->name('comment_reply');
        Route::post('destroy', 'CommentController@destroy')->name('comment_destroy');
    });
    // 友链
    Route::group(['prefix' => 'link'], function () {
        Route::get('manage', 'LinkController@manage')->name('link_manage');

app/Models/Article.php
<?php

namespace App\Models;

use App\Helpers\Extensions\Tool;
use Illuminate\Database\Eloquent\SoftDeletes;

class Article extends Base
{
    use SoftDeletes;

    const PUBLISHED = 1;
    const UNPUBLISHED = 0;
    const ALLOW_COMMENT = 1;
    const FORBID_COMMENT = 0;

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function category()
    {
        return $this->belongsTo(Category::class);
    }


    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsToMany
     */
    public function tags()
    {
        return $this->belongsToMany(Tag::class, 'article_tags');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function comments()
    {
        return $this->hasMany(Comment::class);
    }

    /**
     * @return \Illuminate\Database\Eloquent\Builder|\Illuminate\Database\Eloquent\Model|null|object
     */
    public function getFeedAttribute()
    {
        return Feed::query()->where([
            'target_type' => Feed::TYPE_ARTICLE,
            'target_id' => $this->attributes['id'],
        ])->first();
    }

    /**
     * @return array
     */
    public function getTagIdsAttribute()
    {
        return ArticleTag::query()->where('article_id', $this->attributes['id'])->pluck('tag_id')->toArray();
    }

    /**
     * @return int
     */
    public function getCommentCountAttribute()
    {
        return Comment::query()->where(['article_id' => $this->attributes['id'], 'status' => Comment::CHECKED])->count();
    }

    /**
     * @return mixed
     */
    public function getFeedUpdatedAtAttribute()
    {
        return Feed::query()->where(['target_type' => Feed::TYPE_ARTICLE, 'target_id' => $this->attributes['id']])->value('updated_at');
    }

    /**
     * 获取状态标签
     * @return string
     */
    public function getStatusTagAttribute()
    {
        return $this->attributes['status'] === self::PUBLISHED ? '<a href="javascript:void(0)" class="btn btn-sm btn-success btn-flat">显示</a>' : '<a href="javascript:void(0)" class="btn btn-sm btn-danger btn-flat">隐藏</a>';
    }

    /**
     * 过滤描述中的换行。
     *
     * @param  string $value
     * @return string
     */
    public function getDescriptionAttribute($value)
    {
        return str_replace(["\r", "\n", "\r\n"], '', $value);
    }

    /**
     * 添加文章
     *
     * @param array $data
     * @return bool|mixed
     */
    public function storeData($data)
    {
        $tag_ids = $data['tag_ids'];
        $feed['content'] = $data['content'];
        $feed['html'] = Tool::markdown2Html($data['content']);
        // 如果没有描述;则截取文章内容的前200字作为描述
        if (empty($data['description'])) {
            $description = preg_replace(array('/[~*>#-]*/', '/!?\[.*\]\(.*\)/', '/\[.*\]/'), '', $data['content']);
            $data['description'] = Tool::subStr($description, 0, 150, true);
        }
        unset($data['tag_ids']);
        unset($data['content']);
        //添加数据
        $result = parent::storeData($data);
        Tool::bdPush($result);
        if ($result) {
            // 给文章添加标签
            $articleTag = new ArticleTag;
            $articleTag->addTagIds($result, $tag_ids);
            // 保存feed
            Feed::query()->create([
                'target_type' => Feed::TYPE_ARTICLE,
                'target_id' => $result,
                'content' => $feed['content'],
                'html' => $feed['html'],
            ]);
            Tool::syncRank($result);
            return $result;
        } else {
            return false;
        }
    }

    /**
     * @param int $id
     * @param array $data
     * @return bool
     */
    public function updateData($id, $data)
    {
        $tag_ids = $data['tag_ids'];
        $feed['content'] = $data['content'];
        $feed['html'] = Tool::markdown2Html($data['content']);
        // 如果没有描述;则截取文章内容的前150字作为描述
        if (empty($data['description'])) {
            $description = preg_replace(array('/[~*>#-]*/', '/!?\[.*\]\(.*\)/', '/\[.*\]/'), '', $data['content']);
            $data['description'] = Tool::subStr($description, 0, 150, true);
        }
        unset($data['tag_ids']);
        unset($data['content']);
        $result = parent::updateData(['id' => $id], $data);
        if ($result) {
            $articleTagModel = new ArticleTag;
            $articleTagModel->addTagIds($id, $tag_ids);
            // 保存feed
            Feed::query()->where([
                ['target_type', '=', Feed::TYPE_ARTICLE],
                ['target_id', '=', $id]
            ])->update([
                'content' => $feed['content'],
                'html' => $feed['html'],
            ]);
            return $result;
        } else {
            return false;
        }
    }

}

resources/views/home/archive.blade.php
@extends('layouts.frontend')
@section('title', '文章归档')
@section('keywords', $config['site_keywords'])
@section('description', $config['site_description'])
@section('content')
    <div class="col-md-8">
        <ul class="timeline">
            @foreach($archive as $archive_t)
                <li class="time-label">
                    <span class="bg-black">
                        {{$archive_t->time}}（共{{$archive_t->posts}}篇）
                    </span>
                </li>

                    <li>
                        <i class="fa fa-flag bg-blue"></i>

                        <div class="timeline-item">
                            <span class="time">
                                <i class="fa fa-clock-o"></i> {{$archive_t->time}}</span>

                            <h3 class="timeline-header">{{$archive_t->time}} 共{{$archive_t->posts}}篇文章</h3>

                            <div class="timeline-body">
                                <ul class="list-group list-group-unbordered">
                                    @foreach($archive_t->articles as $article)
                                        <li class="list-group-item">
                                            <a href="{{route('article',$article->id)}}" class="title-link"><i class="fa fa-circle-o"></i>&nbsp;{{$article->title}}</a>
                                        </li>
                                    @endforeach
                                </ul>
                            </div>
                            <div class="timeline-footer">
                            </div>
                        </div>
                    </li>
                @endforeach
            <div class="text-center" >
                {{ $archive->links() }}
            </div>
        </ul>
    </div>
@stop

resources/views/home/category.blade.php
@extends('layouts.frontend')
@section('title', $category->name)
@section('keywords', $category->keywords)
@section('description', $category->description)
@section('content')
    <div class="col-md-8">
        @if(blank($articles))
            <div class="callout callout-danger">
                <h4>Oops！</h4>
                <p>未找到相关文章</p>
            </div>
        @else
        <div class="box box-default">
            <div class="box-header with-border">
                <h3 class="box-title">栏目：<span class="text-red">{{$category->name}}</span></h3>
            </div>
            <div class="box-body">
                <p>@foreach($childCategoryList as $childCategory)<a href="{{route('category',$childCategory->id)}}" class="btn btn-flat bg-blue tag">{{$childCategory->name}}</a>@endforeach</p>
            </div>
        </div>
        @foreach($articles as $article)
            <div class="box box-solid">
                <div class="box-body article-body">
                    <a href="{{route('article',$article->id)}}" class="title-link">
                        <h3>
                            {{$article->title}}
                        </h3>
                    </a>
                    <div class="small m-b-xs">
                        <strong>{{$article->author}}</strong>&nbsp;&nbsp;<span class="text-muted"><i class="fa fa-clock-o"></i>&nbsp;最后更新于&nbsp;{{\App\Helpers\Extensions\Tool::transformTime($article->feed_updated_at)}}</span>
                    </div>
                    <div class="description">
                        <p style="word-wrap:break-word;">{{$article->description}}</p>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <h5>标签：</h5>
                            @foreach($article->tags as $tag)
                                <a href="{{route('tag',$tag->id)}}" @switch(($tag->id)%5) @case(0)class="tag btn btn-flat btn-xs bg-black" @break @case(1)class="tag btn btn-flat btn-xs bg-olive" @break @case(2)class="tag btn btn-flat btn-xs bg-blue" @break @case(3)class="tag btn btn-flat btn-xs bg-purple" @break @default class="tag btn btn-flat btn-xs bg-maroon" @endswitch><i class="fa fa-tag"></i>&nbsp;{{$tag->name}}</a>
                            @endforeach
                        </div>
                        <div class="col-md-6">
                            <div class="small text-right">
                                <h5>状态：</h5>
                                <div><i class="fa fa-comments-o"> </i> {{ $article->comment_count }} 评论</div>
                                <i class="fa fa-eye"> </i> {{$article->click}} 浏览
                            </div>
                        </div>
                    </div>
                    <div class="hr-line-dashed"></div>
                    <div class="row">
                        <div class="col-md-12">
                            <div class="pull-right">
                                <a href="{{route('article',$article->id)}}" class="btn btn-flat bg-black tag"><i class="fa fa-eye"></i> 阅读全文</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        @endforeach
        {{$articles->links()}}
        @endif
    </div>
@stop

resources/views/home/close.blade.php
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <title>关站中</title>
</head>
<body>
<div style="text-align:center">
    <h2>{{$config['site_close_word']}}</h2>
</div>
</body>
</html>

resources/views/home/index.blade.php
@extends('layouts.frontend')
@section('title', $config['site_title'])
@section('keywords', $config['site_keywords'])
@section('description', $config['site_description'])
@section('content')
    <div class="col-md-8">
        <div class="box box-default">
            <div class="box-header with-border">
                <i class="fa fa-bullhorn"></i>

                <h3 class="box-title">网站公告</h3>
            </div>
            <div class="box-body">
                <p>{{$config['site_info']}}</p>
            </div>
        </div>
        @foreach($articles as $article)
            <div class="box box-solid">
                <div class="box-body article-body">
                    <a href="{{route('article',$article->id)}}" class="title-link">
                        <h3>
                            {{$article->title}}
                        </h3>
                    </a>
                    <div class="small m-b-xs">
                        <strong>{{$article->author}}</strong>&nbsp;&nbsp;<span class="text-muted"><i class="fa fa-clock-o"></i>&nbsp;最后更新于&nbsp;{{\App\Helpers\Extensions\Tool::transformTime($article->feed_updated_at)}}</span>
                    </div>
                    <div class="description">
                        <p style="word-wrap:break-word;">{{$article->description}}</p>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <h5>标签：</h5>
                            @foreach($article->tags as $tag)
                                <a href="{{route('tag',$tag->id)}}" @switch(($tag->id)%5) @case(0)class="tag btn btn-flat btn-xs bg-black" @break @case(1)class="tag btn btn-flat btn-xs bg-olive" @break @case(2)class="tag btn btn-flat btn-xs bg-blue" @break @case(3)class="tag btn btn-flat btn-xs bg-purple" @break @default class="tag btn btn-flat btn-xs bg-maroon" @endswitch><i class="fa fa-tag"></i>&nbsp;{{$tag->name}}</a>
                            @endforeach
                        </div>
                        <div class="col-md-6">
                            <div class="small text-right">
                                <h5>状态：</h5>
                                <div><i class="fa fa-comments-o"> </i> {{ $article->comment_count }} 评论</div>
                                <i class="fa fa-eye"> </i> {{$article->click}} 浏览
                            </div>
                        </div>
                    </div>
                    <div class="hr-line-dashed"></div>
                    <div class="row">
                        <div class="col-md-12">
                            <div class="pull-right">
                                <a href="{{route('article',$article->id)}}" class="btn btn-flat bg-black tag"><i class="fa fa-eye"></i> 阅读全文</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        @endforeach
        {{ $articles->links() }}
    </div>
@stop

resources/views/home/message.blade.php
@extends('layouts.frontend')
@section('title', '留言板')
@section('content')
    <div class="col-md-8">
        <div class="box box-solid">
            <div class="box-body">
                <div class="row">
                    <div class="col-md-12">
                        <div class="text-center">
                            <h3>
                                留言板
                            </h3>
                            <p>在这里您可以对网站提出建议，或咨询相关问题</p>
                            <div class="hr-line-dashed"></div>
                        </div>
                        @foreach($messages as $message)
                        <div class="post">
                            <div class="user-block">
                                <img class="img-circle img-bordered-sm" src="{{asset('img/user_avatar.png')}}" alt="{{$message->nickname}}">
                                <span class="username">
                                <a href="#">{{ $message->nickname }}</a>
                                </span>
                                <span class="description">{{ $message->created_at }}</span>
                            </div>
                            <!-- /.user-block -->
                            <p>
                                {{ $message->content }}
                            </p>
                            @isset($message->reply)
                                <div class="post reply-post">
                                    <div class="user-block">
                                        <img class="img-circle img-bordered-sm" src="{{ $config['site_admin_avatar'] }}" alt="{{ $config['site_admin'] }}">
                                        <span class="username">
                                            <a href="#">站长回复</a>
                                        </span>
                                        <span class="description">{{ $message->updated_at }}</span>
                                    </div>
                                    <p>
                                        {{ $message->reply }}
                                    </p>
                                </div>
                            @endisset
                        </div>
                        @endforeach
                        <div class="post clearfix">
                            <h4 class="text-bold">给我留言：</h4>
                            @include('errors.validator')
                            <form role="form" action="{{route('message_store')}}" method="post">
                                @csrf
                                <div class="row">
                                    <div class="col-xs-12 form-group">
                                        <textarea class="form-control" style="resize: none;" rows="3" cols="4" name="content" placeholder="请输入留言" required></textarea>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-md-4 form-group">
                                        <input type="text" class="form-control" name ="nickname"placeholder="输入留言显示名称 *" required>
                                    </div>
                                    <div class="col-md-4 form-group">
                                        <input type="email" class="form-control" name="email" placeholder="输入电子邮件（不会显示）*" required>
                                    </div>
                                    <div class="col-md-4 form-group">
                                        <button type="submit" class="btn btn-flat btn-block bg-green">留言</button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@stop

resources/views/home/subscribe.blade.php
@extends('layouts.frontend')
@section('title', '订阅')
@section('content')
    <div class="col-md-8">
        <div class="box box-solid">
            <div class="box-body">
                <div class="row">
                    <div class="col-md-12">
                        <div class="text-center">
                            <h3>
                                订阅
                            </h3>
                            <p>如果您需要及时了解本站最新发布的文章和消息，您可以通过邮箱订阅本站</p>
                            <div class="hr-line-dashed"></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="box box-solid">
            <div class="box-body">
                <div class="row">
                    <div class="col-md-12">
                        <div class="">
                            @include('errors.validator')
                            <form action="{{ route('subscribe_store') }}" method="post">
                                @csrf
                                <div class="input-group">
                                    <input type="email" class="form-control" name="email" id="subscribe-email" placeholder="请输入订阅邮箱" required><span class="input-group-btn"><button type="submit" class="btn btn-success btn-flat"><i class="fa fa-check"></i></button></span>
                                </div>
                                <span class="help-block text-red">如需解除订阅请联系站长</span>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@stop

resources/views/home/tag.blade.php
@extends('layouts.frontend')
@section('title', $tag->name)
@section('content')
    <div class="col-md-8">
        @if(blank($articles))
            <div class="callout callout-danger">
                <h4>Oops！</h4>
                <p>未找到相关文章</p>
            </div>
        @else
        <div class="box box-solid">
            <div class="box-body">
                 <h3>与<span class="text-red">"{{$tag->name}}"</span>相关的文章</h3>
            </div>
        </div>
        @foreach($articles as $article)
            <div class="box box-solid">
                <div class="box-body article-body">
                    <a href="{{route('article',$article->id)}}" class="title-link">
                        <h3>
                            {{$article->title}}
                        </h3>
                    </a>
                    <div class="small m-b-xs">
                        <strong>{{$article->author}}</strong>&nbsp;&nbsp;<span class="text-muted"><i class="fa fa-clock-o"></i>&nbsp;最后更新于&nbsp;{{\App\Helpers\Extensions\Tool::transformTime($article->feed_updated_at)}}</span>
                    </div>
                    <div class="description">
                        <p style="word-wrap:break-word;">{{$article->description}}</p>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <h5>标签：</h5>
                            @foreach($article->tags as $tag)
                                <a href="{{route('tag',$tag->id)}}" @switch(($tag->id)%5) @case(0)class="tag btn btn-flat btn-xs bg-black" @break @case(1)class="tag btn btn-flat btn-xs bg-olive" @break @case(2)class="tag btn btn-flat btn-xs bg-blue" @break @case(3)class="tag btn btn-flat btn-xs bg-purple" @break @default class="tag btn btn-flat btn-xs bg-maroon" @endswitch><i class="fa fa-tag"></i>&nbsp;{{$tag->name}}</a>
                            @endforeach
                        </div>
                        <div class="col-md-6">
                            <div class="small text-right">
                                <h5>状态：</h5>
                                <div><i class="fa fa-comments-o"> </i> {{ $article->comment_count }} 评论</div>
                                <i class="fa fa-eye"> </i> {{$article->click}} 浏览
                            </div>
                        </div>
                    </div>
                    <div class="hr-line-dashed"></div>
                    <div class="row">
                        <div class="col-md-12">
                            <div class="pull-right">
                                <a href="{{route('article',$article->id)}}" class="btn btn-flat bg-black tag"><i class="fa fa-eye"></i> 阅读全文</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        @endforeach
        {{$articles->links()}}
        @endif
    </div>
@stop