routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// 后台登陆
Route::group(['namespace' => 'Auth'], function () {
    Route::get('login', 'LoginController@showLoginForm')->name('login');
    Route::post('login', 'LoginController@login');
    Route::post('logout', 'LoginController@logout')->name('logout');
    Route::get('password/reset', 'ForgotPasswordController@showLinkRequestForm')->name('password.request');
    Route::post('password/email', 'ForgotPasswordController@sendResetLinkEmail')->name('password.email');
    Route::get('password/reset/{token}', 'ResetPasswordController@showResetForm')->name('password.reset');
    Route::post('password/reset', 'ResetPasswordController@reset');
    // 第三方登录
    Route::group(['prefix' => 'oauth'], function () {
        // 重定向
        Route::get('redirect/{service}', 'OAuthController@redirectToProvider')->name('oauth.redirect');
        // 获取用户资料并登录
        Route::get('callback/{service}', 'OAuthController@handleProviderCallback')->name('oauth.callback');
        // 退出登录
        Route::get('logout', 'OAuthController@logout');
    });
    Route::post('hook/{type}', 'HookController@push');
});

// 前台
Route::group(['namespace' => 'Home', 'middleware' => ['check_status']], function () {
    Route::get('/', 'HomeController@index')->name('home');
    Route::get('about', 'HomeController@about')->name('about');
    Route::get('article/{id}', 'HomeController@article')->name('article');
    Route::get('page/{id}', 'HomeController@page')->name('page');
    Route::post('comment_store', 'HomeController@comment_store')->name('comment_store');
    Route::get('category/{id}', 'HomeController@category')->name('category');
    Route::get('tag/{id}', 'HomeController@tag')->name('tag');
    Route::get('archive', 'HomeController@archive')->name('archive');
    Route::get('message', 'HomeController@message')->name('message');
    Route::post('message_store', 'HomeController@message_store')->name('message_store');
    Route::get('subscribe', 'HomeController@subscribe')->name('subscribe');
    Route::post('subscribe_store', 'HomeController@subscribe_store')->name('subscribe_store');
    Route::get('search', 'HomeController@search')->name('search');
});
// 后台
Route::group(['namespace' => 'Admin', 'prefix' => 'admin', 'middleware' => ['auth:web', 'check_timeout', 'check_permission']], function () {
    // 权限管理
    Route::group(['namespace' => 'Permission'], function () {
        // 角色
        Route::group(['prefix' => 'role'], function () {
            Route::get('manage', 'RoleController@manage')->name('role_manage');
            Route::post('store', 'RoleController@store')->name('role_store');
            Route::get('edit/{id}', 'RoleController@edit')->name('role_edit');
            Route::post('update/{id}', 'RoleController@update')->name('role_update');
            Route::post('destroy', 'RoleController@destroy')->name('role_destroy');
            Route::get('search', 'RoleController@search')->name('role_search');
        });
        // 权限
        Route::group(['prefix' => 'permission'], function () {
            Route::get('manage', 'PermissionController@manage')->name('permission_manage');
            Route::post('store', 'PermissionController@store')->name('permission_store');
            Route::get('edit/{id?}', 'PermissionController@edit')->name('permission_edit');
            Route::post('update', 'PermissionController@update')->name('permission_update');
            Route::post('destroy', 'PermissionController@destroy')->name('permission_destroy');
            Route::get('search', 'PermissionController@search')->name('permission_search');
        });
        // 用户
        Route::group(['prefix' => 'user'], function () {
            Route::get('manage', 'UserController@manage')->name('user_manage');
            Route::get('create', 'UserController@create')->name('user_create');
            Route::post('store', 'UserController@store')->name('user_store');
            Route::get('edit/{id}', 'UserController@edit')->name('user_edit');
            Route::post('update/{id}', 'UserController@update')->name('user_update');
            Route::post('delete', 'UserController@delete')->name('user_delete');
            Route::get('trash', 'UserController@trash')->name('user_trash');
            Route::post('restore', 'UserController@restore')->name('user_restore');
            Route::post('destroy', 'UserController@destroy')->name('user_destroy');
            Route::get('search', 'UserController@search')->name('user_search');
        });
    });
    // 控制台
    Route::get('/', function () {
        return redirect()->route('dashboard_home');
    });
    Route::get('home', 'DashboardController@home')->name('dashboard_home');
    Route::get('clear', 'DashboardController@clear')->name('cache_clear');
    // 配置
    Route::group(['prefix' => 'config'], function () {
        Route::get('manage', 'ConfigController@manage')->name('config_manage');
        Route::post('update', 'ConfigController@update')->name('config_update');
        Route::post('upload-image', 'ConfigController@uploadImage')->name('water_mark_upload');
    });
    // 个人资料
    Route::group(['prefix' => 'profile'], function () {
        Route::get('manage', 'ProfileController@manage')->name('profile_manage');
        Route::post('uploadAvatar', 'ProfileController@uploadAvatar')->name('avatar_upload');
        Route::post('updatePassword', 'ProfileController@updatePassword')->name('password_update');
        Route::post('updateProfile', 'ProfileController@updateProfile')->name('profile_update');
        Route::post('unbindThirdLogin', 'ProfileController@unbindThirdLogin')->name('unbind_third_login');
    });
    // 标签
    Route::group(['prefix' => 'tag'], function () {
        Route::get('manage', 'TagController@manage')->name('tag_manage');
        Route::post('store', 'TagController@store')->name('tag_store');
        Route::get('edit/{id?}', 'TagController@edit')->name('tag_edit');
        Route::post('update', 'TagController@update')->name('tag_update');
        Route::post('destroy', 'TagController@destroy')->name('tag_destroy');
        Route::get('search', 'TagController@search')->name('tag_search');
    });
    // 栏目
    Route::group(['prefix' => 'category'], function () {
        Route::get('manage', 'CategoryController@manage')->name('category_manage');
        Route::get('create', 'CategoryController@create')->name('category_create');
        Route::post('store', 'CategoryController@store')->name('category_store');
        Route::get('edit/{id}', 'CategoryController@edit')->name('category_edit');
        Route::post('update/{id}', 'CategoryController@update')->name('category_update');
        Route::post('destroy', 'CategoryController@destroy')->name('category_destroy');
    });
    // 菜单
    Route::group(['prefix' => 'nav'], function () {
        Route::get('manage', 'NavController@manage')->name('nav_manage');
        Route::get('create', 'NavController@create')->name('nav_create');
        Route::post('store', 'NavController@store')->name('nav_store');
        Route::get('edit/{id}', 'NavController@edit')->name('nav_edit');
        Route::post('update/{id}', 'NavController@update')->name('nav_update');
        Route::post('destroy', 'NavController@destroy')->name('nav_destroy');
    });
    // 文章
    Route::group(['prefix' => 'article'], function () {
        Route::get('manage', 'ArticleController@manage')->name('article_manage');
        Route::get('create', 'ArticleController@create')->name('article_create');
        Route::post('store', 'ArticleController@store')->name('article_store');
        Route::get('edit/{id}', 'ArticleController@edit')->name('article_edit');
        Route::post('update/{id}', 'ArticleController@update')->name('article_update');
        Route::post('delete', 'ArticleController@delete')->name('article_delete');
        Route::get('trash', 'ArticleController@trash')->name('article_trash');
        Route::post('restore', 'ArticleController@restore')->name('article_restore');
        Route::post('destroy', 'ArticleController@destroy')->name('article_destroy');
        Route::post('upload-image', 'ArticleController@uploadImage')->name('article_image_upload');

    });
    // 单页
    Route::group(['prefix' => 'page'], function () {
        Route::get('manage', 'PageController@manage')->name('page_manage');
        Route::get('create', 'PageController@create')->name('page_create');
        Route::post('store', 'PageController@store')->name('page_store');
        Route::get('edit/{id}', 'PageController@edit')->name('page_edit');
        Route::post('update/{id}', 'PageController@update')->name('page_update');
        Route::post('delete', 'PageController@delete')->name('page_delete');
        Route::get('trash', 'PageController@trash')->name('page_trash');
        Route::post('restore', 'PageController@restore')->name('page_restore');
        Route::post('destroy', 'PageController@destroy')->name('page_destroy');
    });
    // 评论
    Route::group(['prefix' => 'comment'], function () {
        Route::get('manage', 'CommentController@manage')->name('comment_manage');
        Route::get('show/{id?}', 'CommentController@show')->name('comment_show');
        Route::post('check', 'CommentController@check')->name('comment_check');
        Route::post('reply', 'CommentController@reply')->name('comment_reply');
        Route::post('destroy', 'CommentController@destroy')->name('comment_destroy');
    });
    // 友链
    Route::group(['prefix' => 'link'], function () {
        Route::get('manage', 'LinkController@manage')->name('link_manage');

app/Models/Nav.php
<?php

namespace App\Models;

class Nav extends Base
{
    const TYPE = [
        0 => '空菜单',
        1 => '分类菜单',
        2 => '归档',
        3 => '单页',
        4 => '外链',
    ];
    const TYPE_EMPTY = 0;    // 普通菜单 可添加单页 链接
    const TYPE_MENU = 1;     // 分类菜单（固定存在的）
    const TYPE_ARCHIVE = 2;  // 归档页面（固定存在的）
    const TYPE_PAGE = 3;     // 单页（url为单页链接）
    const TYPE_LINK = 4;     // 链接（直接添加链接）
    const LIMIT_NUM = 14;    // 最大菜单数
    const STATUS_DISPLAY = 1;
    const STATUS_HIDE = 0;


    /**
     * 递归获取树形索引
     * @param integer
     * @param integer
     * @return array 角色数组
     */
    public function getTreeIndex($id = 0, $deep = 0)
    {
        static $tempArr = [];
        $data = $this->query()->where('parent_id', $id)->orderBy('sort', 'asc')->get();
        foreach ($data as $k => $v) {
            $v->deep = $deep;
            $v->name = str_repeat("&nbsp;&nbsp;", $v->deep * 2) . '|--' . $v->name;
            $tempArr[] = $v;
            $this->getTreeIndex($v->id, $deep + 1);
        }
        return $tempArr;
    }

    public function getTypeNameAttribute()
    {
        $result = "";
        foreach (self::TYPE as $key => $type) {
            if ($this->attributes['type'] == $key) {
                $result = $type;
            }
        }
        return $result;
    }

    public function getStatusTagAttribute()
    {
        return $this->attributes['status'] === self::STATUS_DISPLAY ? '<a href="javascript:void(0)" class="btn btn-sm btn-success btn-flat">显示</a>' : '<a href="javascript:void(0)" class="btn btn-sm btn-danger btn-flat">隐藏</a>';
    }
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;
use App\Notifications\ResetPasswordNotification;
use Spatie\Permission\Models\Role;
use Spatie\Permission\Traits\HasRoles;

class User extends Authenticatable
{
    use Notifiable, HasRoles, SoftDeletes;

    const ACTIVE = 1;
    const FORBID = 0;
    const SUPERUSER = 1; // 超级管理员ID
    const SUPERADMIN = '超级管理员'; // 超级管理员角色组

    protected $guard_name = 'web';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'avatar', 'email', 'password', 'status', 'last_login_at', 'last_login_ip'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * Send the password reset notification.
     *
     * @param  string $token
     * @return void
     */
    public function sendPasswordResetNotification($token)
    {
        $this->notify(new ResetPasswordNotification($token));
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function oauthInfos()
    {
        return $this->hasMany(OauthInfo::class);
    }

    public function getStatusTagAttribute()
    {
        return $this->attributes['status'] === self::ACTIVE ? '<a href="javascript:void(0)" class="btn btn-sm btn-success btn-flat">正常</a>' : '<a href="javascript:void(0)" class="btn btn-sm btn-danger btn-flat">禁用</a>';
    }

    public function getAllRolesTagAttribute()
    {
        $role_tags = '';
        $roles = Role::all();
        foreach ($roles as $role) {
            if ($this->hasRole($role->name)) {
                $role_tags .= '&nbsp;<a href="javascript:void(0)" class="btn btn-sm btn-success btn-flat">' . $role->name . '</a>';
            }
        }
        return $role_tags;
    }
}

app/Http/Controllers/Admin/Permission/PermissionController.php
<?php

namespace App\Http\Controllers\Admin\Permission;

use App\Models\User;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Spatie\Permission\Models\Permission;
use App\Http\Requests\Permission\Store;
use App\Http\Requests\Permission\Update;
use Illuminate\Support\Facades\DB;
use Spatie\Permission\Models\Role;
use App\Helpers\Extensions\Tool;

/**权限管理
 * Class PermissionController
 * @package App\Http\Controllers\Admin\Permission
 */
class PermissionController extends Controller
{

    /**
     * 权限管理列表
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function manage()
    {
        $permissions = Permission::query()->orderBy('route', 'desc')->paginate(12);
        return view('admin.permission.permission', compact('permissions'));

    }

    /**
     * 权限增加
     * @param Store $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(Store $request)
    {
        $name = $request->get('name');
        $route = $request->get('route');
        $createOrFail = Permission::create(['name' => $name, 'route' => $route]);
        // 同步更新权限到超级管理员
        $role = Role::findByName(User::SUPERADMIN);
        $role->givePermissionTo($name);
        $createOrFail ? Tool::showMessage('添加成功') : Tool::showMessage('添加失败',false) ;
        Tool::recordOperation(auth()->user()->name,'添加权限');
        return redirect()->back();
    }

    /**
     * 权限修改
     * @param null $id
     * @return \Illuminate\Http\JsonResponse
     */
    public function edit( $id = null )
    {
        if (is_null($id)) {
            return abort(404, '对不起，找不到相关页面');
        }
        if (!$response = Permission::findById($id)) {
            return Tool::ajaxReturn(404, ['alert' => '未找到相关数据']);
        }
        return Tool::ajaxReturn(200, $response);
    }

    /**
     * @param Update $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update(Update $request)
    {
        $id = $request->get('id');
        $name=$request->get('edit_name');
        $route=$request->get('edit_route');
        $permission = Permission::query()->findOrFail($id);
        if(!$permission) {
            Tool::showMessage('未查到相关，添加失败', false);
            return redirect()->back();
        }
        $saveOrFail = $permission->update([
            'name' => $name,
            'route' => $route
        ]);
        $saveOrFail ? Tool::showMessage('修改成功'): Tool::showMessage('修改失败',false);
        Tool::recordOperation(auth()->user()->name,'修改权限');
        return redirect()->back();

    }

    /**
     * 权限删除
     * @param Request $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function destroy(Request $request)
    {
        $data = $request->only('pid');
        $arr = explode(',', $data['pid']);
        DB::table('model_has_permissions')->whereIn('permission_id',$arr)->delete();
        DB::table('role_has_permissions')->whereIn('permission_id',$arr)->delete();
        $deleteOrFail = Permission::query()->whereIn('id',$arr)->delete();
        $deleteOrFail ? Tool::showMessage('删除成功') : Tool::showMessage('删除失败',false);
        Tool::recordOperation(auth()->user()->name,'删除权限');
        return redirect()->back();
    }

    /**
     * 搜索
     * @param Request $request
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function search(Request $request)
    {
        $keyword = $request->get('keyword');
        $map = [
            ['name', 'like', '%' . $keyword . '%'],
        ];
        $permissions = Permission::query()->where($map)->orderBy('id', 'desc')->paginate(10);
        return view('admin.permission.permission', compact('permissions'));
    }
}

resources/views/admin/permission/user-trash.blade.php
@extends('layouts.backend')
@section('title','控制台 - 用户小黑屋')
@section('content')
    <div class="content-wrapper">
        <section class="content-header">
            <h1>用户小黑屋<small>LABLOG</small></h1>
            <ol class="breadcrumb">
                <li><a href="{{ route('dashboard_home') }}"><i class="fa fa-dashboard"></i> 首页</a></li>
                <li><a href="#">用户管理</a></li>
                <li class="active">用户小黑屋</li>
            </ol>
        </section>
        <section class="content container-fluid">
            <div class="row">
                <div class="col-md-12">
                    <div class="box">
                        <div class="box-header">
                            <h3 class="box-title">全部删除用户</h3>
                            <span>共 {{ $users->total() }}个</span>
                        </div>
                        <div class="box-body table-responsive no-padding">
                            <table class="table table-hover">
                                <thead>
                                    <tr>
                                        <th>#</th>
                                        <th>ID</th>
                                        <th>用户名</th>
                                        <th>角色</th>
                                        <th>邮箱</th>
                                        <th>用户状态</th>
                                        <th>删除时间</th>
                                        <th>操作</th>
                                    </tr>
                                </thead>
                                <tbody>
                                @if(!blank($users))
                                    @foreach($users as $user)
                                        <tr>
                                            <td><input type="checkbox" value="{{$user->id}}" name="uid" class="i-checks"></td>
                                            <td>{{ $user->id }}</td>
                                            <td>{{ $user->name }}</td>
                                            <td>{!! $user->all_roles_tag !!}</td>
                                            <td>{{ $user->email }}</td>
                                            <td>{!! $user->status_tag !!}</td>
                                            <td>{{ $user->deleted_at }}</td>
                                            <td>
                                                <a class="text-green restoreUser"><i class="fa fa-recycle"></i></a>&nbsp;&nbsp;
                                                <a class="text-red destroyUser"><i class="fa fa-trash"></i></a>
                                            </td>
                                        </tr>
                                    @endforeach
                                @else
                                    <tr><td valign="top" colspan="8">表中数据为空</td></tr>
                                @endif
                                </tbody>
                            </table>
                            <form id="restoreForm" style="display: none;" method="POST" action="{{route('user_restore')}}">
                                @csrf
                                <input type="hidden" name="uid" id="restoreId">
                            </form>
                            <form id="destroyForm" style="display: none;" method="POST" action="{{route('user_destroy')}}">
                                @csrf
                                <input type="hidden" name="uid" id="destroyId">
                            </form>
                        </div>
                        <div class="box-footer clearfix">
                            <div class="pull-left">
                                <a href="javascript:void(0)" class="btn btn-primary btn-flat" onclick="selectAll('uid')">全选</a>
                                <a href="javascript:void(0)" class="btn btn-primary btn-flat" onclick="selectEmpty('uid')">全不选</a>
                                <a href="javascript:void(0)" class="btn btn-primary btn-flat" onclick="selectReverse('uid')">反选</a>
                                <a href="javascript:void(0)" class="btn btn-danger btn-flat" id="destroySelectedUser">彻底删除选定</a>
                                <a href="javascript:void(0)" class="btn btn-success btn-flat" id="restoreSelectedUser">恢复选定</a>
                            </div>
                            @if(request()->has('keyword'))
                                {{ $users->appends(['keyword' => request()->input('keyword')])->links('vendor.pagination.adminlte') }}
                            @else
                                {{ $users->links('vendor.pagination.adminlte') }}
                            @endif
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>
@stop

resources/views/admin/permission/user.blade.php
@extends('layouts.backend')
@section('title','控制台 - 用户管理')
@section('content')
    <div class="content-wrapper">
        <section class="content-header">
            <h1>用户管理<small>LABLOG</small></h1>
            <ol class="breadcrumb">
                <li><a href="{{ route('dashboard_home') }}"><i class="fa fa-dashboard"></i> 首页</a></li>
                <li><a href="#">权限管理</a></li>
                <li class="active">用户管理</li>
            </ol>
        </section>
        <section class="content container-fluid">
            <div class="row">
                <div class="col-md-12">
                    <div class="box box-solid">
                        <div class="box-body">
                            <a href="{{ route('user_create') }}" class="btn btn-success btn-flat" ><i class="fa fa-user-plus"></i>&nbsp;添加用户</a>&nbsp;&nbsp;
                            <a href="{{ route('user_trash') }}" class="btn btn-danger btn-flat" ><i class="fa fa-user"></i>&nbsp;小黑屋</a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <div class="box">
                        <div class="box-header">
                            <h3 class="box-title">全部用户</h3>
                            <span>共 {{ $users->total() }}个</span>
                            <form action="{{ route('user_search') }}" method="get" style="display: inline-flex" class="pull-right">
                                <div class="box-tools">
                                    <div class="input-group input-group-sm" style="width: 150px;">
                                        <input type="text" name="keyword" class="form-control" placeholder="搜索">

                                        <span class="input-group-btn">
                                            <button type="submit" class="btn btn-default"><i class="fa fa-search"></i></button>
                                        </span>
                                    </div>
                                </div>
                            </form>
                        </div>
                        <div class="box-body table-responsive no-padding">
                            <table class="table table-hover">
                                <thead>
                                    <tr>
                                        <th>#</th>
                                        <th>ID</th>
                                        <th>用户名</th>
                                        <th>角色</th>
                                        <th>邮箱</th>
                                        <th>用户状态</th>
                                        <th>最后登录</th>
                                        <th>添加时间</th>
                                        <th>操作</th>
                                    </tr>
                                </thead>
                                <tbody>
                                @if(!blank($users))
                                    @foreach($users as $user)
                                    <tr>
                                        <td><input type="checkbox" value="{{$user->id}}" name="uid" class="i-checks"></td>
                                        <td>{{ $user->id }}</td>
                                        <td>{{ $user->name }}</td>
                                        <td>{!! $user->all_roles_tag !!}</td>
                                        <td>{{ $user->email }}</td>
                                        <td>{!! $user->status_tag !!}</td>
                                        <td>{{ $user->last_login_at }}</td>
                                        <td>{{ $user->created_at }}</td>
                                        <td>
                                            <a href="{{ route('user_edit',$user->id) }}" class="text-green">
                                                <i class="fa fa-pencil-square-o"></i>
                                            </a>&nbsp;&nbsp;
                                            <a href="javascript:void(0)" class="text-red delUser">
                                                <i class="fa fa-trash"></i>
                                            </a>
                                        </td>
                                    </tr>
                                @endforeach
                                    @else
                                    <tr><td valign="top" colspan="8">表中数据为空</td></tr>
                                @endif
                                </tbody>
                            </table>
                            <form id="deleteForm" style="display: none;" action="{{ route('user_delete') }}" method="post">
                                @csrf
                                <input type="hidden" name="uid" id="deleteId">
                            </form>
                        </div>
                        <div class="box-footer clearfix">
                            <div class="pull-left">
                                <a href="javascript:void(0)" class="btn btn-primary btn-flat" onclick="selectAll('uid')">全选</a>
                                <a href="javascript:void(0)" class="btn btn-primary btn-flat" onclick="selectEmpty('uid')">全不选</a>
                                <a href="javascript:void(0)" class="btn btn-primary btn-flat" onclick="selectReverse('uid')">反选</a>
                                <a href="javascript:void(0)" class="btn btn-danger btn-flat" id="delSelectedUser">删除选定</a>
                            </div>
                            @if(request()->has('keyword'))
                                {{ $users->appends(['keyword' => request()->input('keyword')])->links('vendor.pagination.adminlte') }}
                            @else
                                {{ $users->links('vendor.pagination.adminlte') }}
                            @endif
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>
@stop